### PR TITLE
Updated microsoft edge download link and md5 sum.

### PR DESCRIPTION
**Pull request by Jamesking56**
Needs testing. I will be testing this in a few hours (when I am on a better internet connection) to see if I can install Microsoft Edge (Windows 10).

References #274

### CODE REVIEW

**Comment by Jamesking56** [comment]
Works but doesn't seem to have guest additions installed.

**Comment by xdissent** [comment]
Ah bummer. I'll check it out when I get out of the office this evening.

**Comment by jmeas** [comment]
Thanks for updating the links, @Jamesking56 ! Is the missing guest additions something we should message Microsoft about?

**Comment by karlhorky** [comment]
I was thinking that as well, but then I took a look at the script and it's installing the guest additions: https://github.com/xdissent/ievms/blob/1de54914fd4a6dc46d34d1830ad1f9535fec5e20/ievms.sh#L243-L252

So my guess is that this method of installation doesn't work with the latest build, or that Guest Additions itself is incompatible with the latest build.

**Comment by Jamesking56** [comment]
This no longer works so I will make a new PR with again a new URL and MD5.

**Pull request closed without merging**
